------------------------------------------------
section ".always_merge"

tDef(0, "3-head")
tDef(0, "3-headed hydra")
tDef(0, "Agrimley the hermit")
tDef(0, "Allied Kingdoms")
tDef(0, "Angolwen")
tDef(0, "Assassin lair")
tDef(0, "Control Room")
tDef(0, "Cosmic Fauna")
tDef(0, "Dreadfell")
tDef(0, "Enemies")
tDef(0, "Experimentation Room")
tDef(0, "Exploratory Farportal")
tDef(0, "FINGER")
tDef(0, "Fearscape")
tDef(0, "Hall of Reflection")
tDef(0, "Horrors")
tDef(0, "Iron Throne")
tDef(0, "Keepers of Reality")
tDef(0, "MAINHAND")
tDef(0, "Marus of Elvala")
tDef(0, "OFFHAND")
tDef(0, "Orc Pride")
tDef(0, "Portal Room")
tDef(0, "Rhalore")
tDef(0, "Sandworm Burrowers")
tDef(0, "Shalore")
tDef(0, "Shasshhiy'Kaish")
tDef(0, "Sher'Tul")
tDef(0, "Slavers")
tDef(0, "Sorcerers")
tDef(0, "Stire of Derth")
tDef(0, "Storage Room")
tDef(0, "Sunwall")
tDef(0, "Temple of Creation")
tDef(0, "Thalore")
tDef(0, "The Way")
tDef(0, [[Today is the %s %s of the %s year of the Age of Ascendancy of Maj'Eyal.
The time is %02d:%02d.]])
tDef(0, "Undead")
tDef(0, "Ungrol of Last Hope")
tDef(0, "Vargh Republic")
tDef(0, "Victim")
tDef(0, "Water lair")
tDef(0, "Zigur")
tDef(0, "absolute")
tDef(0, "armours")
tDef(0, "bomb")
tDef(0, "bonestaff")
tDef(0, "cannister")
tDef(0, "charged")
tDef(0, "combat")
tDef(0, "daikara")
tDef(0, "default")
tDef(0, "demon")
tDef(0, "dragon")
tDef(0, "dream")
tDef(0, "east")
tDef(0, "exit")
tDef(0, "harmonystaff")
tDef(0, "humanoid")
tDef(0, "humanoid/orc")
tDef(0, "husk")
tDef(0, "hydra")
tDef(0, "image")
tDef(0, "injured seer")
tDef(0, "kinetic")
tDef(0, "living")
tDef(0, "lone alchemist")
tDef(0, "lost defiler")
tDef(0, "lost sun paladin")
tDef(0, "lost warrior")
tDef(0, "magestaff")
tDef(0, "magical")
tDef(0, "mainhand")
tDef(0, "melee")
tDef(0, "mental")
tDef(0, "mountain chain")
tDef(0, "movement")
tDef(0, "north")
tDef(0, "northeast")
tDef(0, "northwest")
tDef(0, "offhand")
tDef(0, "portal")
tDef(0, "portal back")
tDef(0, "ranged")
tDef(0, "repented thief")
tDef(0, "rimebark")
tDef(0, "seed")
tDef(0, "south")
tDef(0, "southeast")
tDef(0, "southwest")
tDef(0, "spell")
tDef(0, "standard")
tDef(0, "standby")
tDef(0, "starstaff")
tDef(0, "steambot")
tDef(0, "stone golem")
tDef(0, "summon")
tDef(0, "summoned")
tDef(0, "tank")
tDef(0, "temporal explorer")
tDef(0, "temporal hound")
tDef(0, "thermal")
tDef(0, "throwing")
tDef(0, "turtle")
tDef(0, "unarmed")
tDef(0, "undead")
tDef(0, "unliving")
tDef(0, "unnatural")
tDef(0, "unseen")
tDef(0, "vilestaff")
tDef(0, "volcanic mountains")
tDef(0, "war hound")
tDef(0, "weapons")
tDef(0, "west")
tDef(0, "worried loremaster")
